name: Build and Test

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Run the application (optional)
        run: node index.js
          if [ "${{ steps.run_application.outputs.app_status }}" == "success" ]; then
          echo "Application is running successfully on port 3000."
          exit 0
          else
          echo "Application failed to start."
          exit 1
          fi
